name: Detect Duplicate Issues

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  detect-duplicates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup ollama
        uses: ai-action/setup-ollama@v1

      - name: Cache ollama
        id: cache-ollama
        uses: actions/cache@v4
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama

      - if: ${{ steps.cache-ollama.outputs.cache-hit != 'true' }}
        name: Install model
        run: ollama pull llama3.2:3b

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache python packages
        id: cache-python
        uses: actions/cache@v4
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements.txt') }}

      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: pip install ollama pygithub

      - name: Run duplicate detection
        run: python .github/scripts/duplicate_detection/new_script.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}