name: Detect Duplicate Issues

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  detect-duplicates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.11'
        run: pip install pygithub scikit-learn sentence-transformers

      - name: Run duplicate detection
        run: python .github/workflows/detect_duplicates.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}